language: c

os:
    - osx

osx_image: xcode10.2

compiler:
    - clang

addons:
    homebrew:
        packages: ncurses

install:
    - mkdir tmp
    - cd tmp
    - cmake -G "Unix Makefiles" ..

script:
    - cd tmp
    - make all test

after_success:
    - bash <(curl -s https://codecov.io/bash)
