language: c
jobs:
    include:
        -   os: osx
            osx_image: xcode12.2
            addons:
                homebrew:
                    packages: ncurses
            install:
                - cmake -S . -B build -G "Unix Makefiles" -DCOVERAGE=ON -DHOMEBREW_NCURSES=ON
            script:
                - cmake --build build --target all test
            after_success:
                - bash <(curl -s https://codecov.io/bash)

        -   os: linux
            dist: focal
            before_install:
                - sudo apt-get -y install libbsd-dev
            install:
                - cmake -S . -B build -G "Unix Makefiles"
            script:
                - cmake --build build --target all test
