language: c

os:
    - osx

osx_image: xcode11.5

compiler:
    - clang

addons:
    homebrew:
        packages: ncurses

install:
    - cmake -G "Unix Makefiles" .

script:
    - make all test

after_success:
    - bash <(curl -s https://codecov.io/bash)
#    - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/8b76995ad4a95a61cecd4b049a448a402d91d197/codecov)
