language: c

os:
    - osx

osx_image: xcode11.5

compiler:
    - clang

addons:
    homebrew:
        packages: ncurses

install:
    - cmake -S . -B build -G "Unix Makefiles"

script:
    - cmake --build build --target all test

after_success:
    - bash <(curl -s https://codecov.io/bash)
